#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

. /usr/share/libubox/jshn.sh

wm=NONE

load_lora_mode() {
        json_init
        json_load_file /etc/lorawan_workmode/lorawan_workmode.conf
        json_get_var wm work_mode
        echo $wm
}

start_service() {
        load_lora_mode
        case "$wm" in
	PKFD)
                echo '------packet forwarder starting-----'
                procd_open_instance
                procd_set_param command  /usr/bin/lora_pkt_fwd
                procd_append_param command -c /etc/lora_pkt_fwd/global_conf.json
                #procd_set_param respawn 5 2 0
                procd_set_param stdout 1 # forward stdout of the command to logd
                procd_set_param stderr 1 # same for stderr
                procd_close_instance
                ;;
	*)
	        ;;
	esac
}

reload_service() {
        stop
        start
}
