#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

. /usr/share/libubox/jshn.sh

wm=NONE

load_lora_mode() {
    json_init
    json_load_file /etc/lorawan_workmode/lorawan_workmode.conf
    json_get_var wm work_mode
    echo $wm
}

start_service() {
    load_lora_mode
    timeout=300
    interval=5
    elapsed=0
    while true; do
        eth_status=$(ip link show eth0.2 | awk '/state/ {print $9}')
        usb_status=$(ip link show usb0 | awk '/state/ {print $9}')
        if [[ $eth_status != "UP" && $usb_status != "UP" ]];then
            echo "Network if is down, waiting...."
            sleep $interval
        else
            echo "if up, Network Ready."
            break
        fi
        sleep $interval
        ((elapsed +=interval))
        if ((elapsed >= timeout));then
            echo "Network timeout"
            exit 0
        fi
    done
    if [ "$wm" = "PKFD" ] || [ "$wm" = "BRDG" ]; then
            echo '------packet forwarder starting-----'
            procd_open_instance
            procd_set_param command  /usr/bin/lora_pkt_fwd
            procd_append_param command -c /etc/lora_pkt_fwd/global_conf.json
            #procd_set_param respawn 5 2 0
            procd_set_param stdout 1 # forward stdout of the command to logd
            procd_set_param stderr 1 # same for stderr
            procd_close_instance
    fi

}

reload_service() {
    stop
    start
}
