#!/bin/sh /etc/rc.common

START=15
STOP=60
USE_PROCD=1


start_service(){	
	#[ "$LTE_MODULE" = "0" ] && return
		
	#config_load quectel
	#config_get enable quectel enable 1
	
	#[ "$enable" = "0" ] && return

	procd_open_instance
	procd_set_param command /usr/bin/quectel-CM
	

	#config_get apn quectel apn
	#config_get user quectel user
	#config_get password quectel password
	#config_get pincode quectel pincode
	#config_get ipv6 quectel ipv6 0

	#[ -n "$apn" ] && procd_append_param command -s $apn
	#[ -n "$apn" ] && [ -n "$user" ] && [ -n "$password" ] && procd_append_param command ${user} ${password}
	#[ -n "$pincode" ] && procd_append_param command -p ${pincode}
	#[ "$ipv6" = "1" ] && procd_append_param command -6

	procd_set_param respawn 5 2 0
	procd_close_instance
}

stop_service(){
	service_stop /usr/bin/quectel-CM
}

service_triggers(){
	#killall quectel-CM
	#ifup wan
	procd_add_reload_trigger "quectel"
}

reload_service(){
	stop 
	start
}