#!/bin/sh /etc/rc.common

START=101
STOP=10
USE_PROCD=1

start_service() {
    echo "Start lora gateway bridge..."
    procd_open_instance
    procd_set_param command  /usr/bin/lora-gateway-bridge
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    service_stop /usr/bin/lora-gateway-bridge
}

reload_service() {
    stop
    start
}
