#!/bin/sh /etc/rc.common

START=101
STOP=10
USE_PROCD=1

start_service() {
    echo "Start network-monitor..."
    procd_open_instance
    procd_set_param command  /usr/bin/netlink-monitor
    procd_close_instance
}

stop_service() {
    process_name="netlink-monitor"

    pid=$(pgrep $process_name)
    if [ -n "$pid" ]; then
        echo "Killing process $pid..."
        kill -SIGINT $pid

    else
        echo "Process $process_name not found."
    fi
}

reload_service() {
    stop
    start
}
